# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestBridge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestBridge

#pod 'iOSDFULibrary'
pod 'Zip'

  target 'TestBridgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestBridgeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
